<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Vugen" productVer="2021" os="" host="DESKTOP-G16F30O"><DocLocation><![CDATA[C:\Users\Solirius\Documents\VuGen\Scripts\LoadRunner2021\006_JudgementTestv2]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[006_JudgementTestv2]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="13/04/2021 - 16:27:26" eTime="13/04/2021 - 16:27:26" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Summary sTime="13/04/2021 - 16:27:30" eTime="13/04/2021 - 16:27:30" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[LaunchHomePage]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://manage-case.perf...tform.hmcts.net/ was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:32]]></Time>
<TimeTick>1618327652</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Sign in's Visible Text contains Sign in was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:33]]></Time>
<TimeTick>1618327653</TimeTick>
<NodeArgs eType="General" icon="0" nRep="12" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:27:30" eTime="13/04/2021 - 16:27:36" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="10" status="Passed" >
<Disp><![CDATA[LaunchHomePage Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T8">
<AName><![CDATA[SignIn]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.1: Click on Email address textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:39]]></Time>
<TimeTick>1618327659</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.2: Type ccdloadtest4504@gmail.com in Email address textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:49]]></Time>
<TimeTick>1618327669</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.3: Click on Email address textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:51]]></Time>
<TimeTick>1618327671</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.4: Click on Password passwordbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:54]]></Time>
<TimeTick>1618327674</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.5: Type ********** in Password passwordbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:27:58]]></Time>
<TimeTick>1618327678</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.6: Click on Sign in button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:00]]></Time>
<TimeTick>1618327680</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1.7: Verify Case List's Visible Text contains Case List was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:02]]></Time>
<TimeTick>1618327682</TimeTick>
<NodeArgs eType="General" icon="0" nRep="21" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:27:36" eTime="13/04/2021 - 16:28:05" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="14" status="Passed" >
<Disp><![CDATA[SignIn Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[SearchCase]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Select Leeds - Singles from Case type listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:08]]></Time>
<TimeTick>1618327688</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Case Number textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:10]]></Time>
<TimeTick>1618327690</TimeTick>
<NodeArgs eType="General" icon="0" nRep="25" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Type 181300558 in Case Number textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:14]]></Time>
<TimeTick>1618327694</TimeTick>
<NodeArgs eType="General" icon="0" nRep="26" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on Apply button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:16]]></Time>
<TimeTick>1618327696</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:28:05" eTime="13/04/2021 - 16:28:19" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="23" status="Passed" >
<Disp><![CDATA[SearchCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T21">
<AName><![CDATA[SelectCase]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Click on ArgsContext.LR.getParam(...seNumberSelect") link was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:21]]></Time>
<TimeTick>1618327701</TimeTick>
<NodeArgs eType="General" icon="0" nRep="30" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Next step's Visible Text contains Next step was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:21]]></Time>
<TimeTick>1618327701</TimeTick>
<NodeArgs eType="General" icon="0" nRep="31" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:28:19" eTime="13/04/2021 - 16:28:24" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="29" status="Passed" >
<Disp><![CDATA[SelectCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T24">
<AName><![CDATA[SelectJudgement]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Select Judgment from Next step listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:26]]></Time>
<TimeTick>1618327706</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Go button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:30]]></Time>
<TimeTick>1618327710</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Verify Judgment's Visible Text contains Judgment was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:30]]></Time>
<TimeTick>1618327710</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:28:24" eTime="13/04/2021 - 16:28:33" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="33" status="Passed" >
<Disp><![CDATA[SelectJudgement Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T28">
<AName><![CDATA[AddNewJudgment]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.1: Click on Add new button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:36]]></Time>
<TimeTick>1618327716</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.3: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:42]]></Time>
<TimeTick>1618327722</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.5: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:48]]></Time>
<TimeTick>1618327728</TimeTick>
<NodeArgs eType="General" icon="0" nRep="41" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.6: Click on Day textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:51]]></Time>
<TimeTick>1618327731</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.7: Type 16 in Day textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:52]]></Time>
<TimeTick>1618327732</TimeTick>
<NodeArgs eType="General" icon="0" nRep="43" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.8: Click on Month textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:55]]></Time>
<TimeTick>1618327735</TimeTick>
<NodeArgs eType="General" icon="0" nRep="44" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.9: Type 03 in Month textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:56]]></Time>
<TimeTick>1618327736</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.10: Click on Year textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:28:59]]></Time>
<TimeTick>1618327739</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.11: Type 2021 in Year textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:01]]></Time>
<TimeTick>1618327741</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1.12: Select Judgment from Judgment Type listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:04]]></Time>
<TimeTick>1618327744</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1.14: Select Reconsideration from Judgment Type listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:09]]></Time>
<TimeTick>1618327749</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1.15: Select Liability from Liability (Optional) listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:12]]></Time>
<TimeTick>1618327752</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.16: Click on Add new button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:15]]></Time>
<TimeTick>1618327755</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1.18: Select ADT from Jurisdiction listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:21]]></Time>
<TimeTick>1618327761</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.19: Click on Day textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:23]]></Time>
<TimeTick>1618327763</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.20: Type 16 in Day textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:26]]></Time>
<TimeTick>1618327766</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.21: Type 03 in Month textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:30]]></Time>
<TimeTick>1618327770</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.22: Type 2021 in Year textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:34]]></Time>
<TimeTick>1618327774</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.23: Type 16 in Day textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:37]]></Time>
<TimeTick>1618327777</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.24: Type 03 in Month textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:40]]></Time>
<TimeTick>1618327780</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.25: Type 2021 in Year textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:43]]></Time>
<TimeTick>1618327783</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[1.26: Type UI Performance test Run 16/03/2021 in Judgment Notes (Optional) textbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:29:59]]></Time>
<TimeTick>1618327799</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.27: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:02]]></Time>
<TimeTick>1618327802</TimeTick>
<NodeArgs eType="General" icon="0" nRep="61" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.28: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:05]]></Time>
<TimeTick>1618327805</TimeTick>
<NodeArgs eType="General" icon="0" nRep="62" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.29: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:08]]></Time>
<TimeTick>1618327808</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.30: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:10]]></Time>
<TimeTick>1618327810</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.31: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:13]]></Time>
<TimeTick>1618327813</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.32: Click on No radio was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:16]]></Time>
<TimeTick>1618327816</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1.34: Click on Continue button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:23]]></Time>
<TimeTick>1618327823</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Judgment's Visible Text contains Judgment was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:23]]></Time>
<TimeTick>1618327823</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:28:33" eTime="13/04/2021 - 16:30:26" passed="30" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="38" status="Passed" >
<Disp><![CDATA[AddNewJudgment Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T59">
<AName><![CDATA[SubmitJudgement]]></AName>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Click on Submit button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:30]]></Time>
<TimeTick>1618327830</TimeTick>
<NodeArgs eType="General" icon="0" nRep="71" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Judgement Added's Visible Text contains has been updated with event: Judgment was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:30]]></Time>
<TimeTick>1618327830</TimeTick>
<NodeArgs eType="General" icon="0" nRep="72" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:30:26" eTime="13/04/2021 - 16:30:33" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="70" status="Passed" >
<Disp><![CDATA[SubmitJudgement Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T62">
<AName><![CDATA[CleanUp]]></AName>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Select Judgment from Next step listbox was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:34]]></Time>
<TimeTick>1618327834</TimeTick>
<NodeArgs eType="General" icon="0" nRep="75" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Go button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:37]]></Time>
<TimeTick>1618327837</TimeTick>
<NodeArgs eType="General" icon="0" nRep="76" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on Remove button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:41]]></Time>
<TimeTick>1618327841</TimeTick>
<NodeArgs eType="General" icon="0" nRep="77" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Click on Remove button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:47]]></Time>
<TimeTick>1618327847</TimeTick>
<NodeArgs eType="General" icon="0" nRep="78" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Continue button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:30:53]]></Time>
<TimeTick>1618327853</TimeTick>
<NodeArgs eType="General" icon="0" nRep="79" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Submit button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:31:00]]></Time>
<TimeTick>1618327860</TimeTick>
<NodeArgs eType="General" icon="0" nRep="80" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Case list link was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:31:05]]></Time>
<TimeTick>1618327865</TimeTick>
<NodeArgs eType="General" icon="0" nRep="81" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Click on Reset button was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:31:09]]></Time>
<TimeTick>1618327869</TimeTick>
<NodeArgs eType="General" icon="0" nRep="82" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:30:33" eTime="13/04/2021 - 16:31:13" passed="8" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="74" status="Passed" >
<Disp><![CDATA[CleanUp Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T71">
<AName><![CDATA[SignOut]]></AName>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Click on Sign out link was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:31:14]]></Time>
<TimeTick>1618327874</TimeTick>
<NodeArgs eType="General" icon="0" nRep="85" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Sign in's Visible Text contains Sign in was finished]]></Details>
<Time><![CDATA[13/04/2021 - 16:31:14]]></Time>
<TimeTick>1618327874</TimeTick>
<NodeArgs eType="General" icon="0" nRep="86" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13/04/2021 - 16:31:13" eTime="13/04/2021 - 16:31:14" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="84" status="Passed" >
<Disp><![CDATA[SignOut Summary]]></Disp>
</NodeArgs>
</Action>