<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Vugen" productVer="2021" os="" host="DESKTOP-G16F30O"><DocLocation><![CDATA[C:\Users\Solirius\Documents\VuGen\Scripts\LoadRunner2021\003_UpdateRespondent_UIPerformanceTestv1]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[003_UpdateRespondent_UIPerformanceTestv1]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="15/04/2021 - 09:42:02" eTime="15/04/2021 - 09:42:02" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Summary sTime="15/04/2021 - 09:42:03" eTime="15/04/2021 - 09:42:03" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[LaunchHomePage]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://manage-case.perf...tform.hmcts.net/ was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:06]]></Time>
<TimeTick>1618476126</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:42:03" eTime="15/04/2021 - 09:42:09" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="10" status="Passed" >
<Disp><![CDATA[LaunchHomePage Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T7">
<AName><![CDATA[SignIn]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Wait until Email address textbox exists was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:09]]></Time>
<TimeTick>1618476129</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Wait]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Wait until Password passwordbox exists was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:09]]></Time>
<TimeTick>1618476129</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Wait]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.1: Click on Email address textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:12]]></Time>
<TimeTick>1618476132</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.2: Type ccdloadtest4506@gmail.com in Email address textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:21]]></Time>
<TimeTick>1618476141</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.3: Click on Password passwordbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:24]]></Time>
<TimeTick>1618476144</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.4: Type ********** in Password passwordbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:28]]></Time>
<TimeTick>1618476148</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.5: Click on Sign in button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:43]]></Time>
<TimeTick>1618476163</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:42:09" eTime="15/04/2021 - 09:42:46" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="13" status="Passed" >
<Disp><![CDATA[SignIn Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[SearchCase]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Case List's Visible Text contains Case List was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:46]]></Time>
<TimeTick>1618476166</TimeTick>
<NodeArgs eType="General" icon="0" nRep="23" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on Case Number textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:52]]></Time>
<TimeTick>1618476172</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Type 181300564 in Case Number textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:42:57]]></Time>
<TimeTick>1618476177</TimeTick>
<NodeArgs eType="General" icon="0" nRep="25" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Apply button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:00]]></Time>
<TimeTick>1618476180</TimeTick>
<NodeArgs eType="General" icon="0" nRep="26" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[6: Click on Apply button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:03]]></Time>
<TimeTick>1618476183</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[7: Select Leeds - Singles from Case type listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:05]]></Time>
<TimeTick>1618476185</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[8: Click on Apply button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:08]]></Time>
<TimeTick>1618476188</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:42:46" eTime="15/04/2021 - 09:43:11" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" status="Passed" >
<Disp><![CDATA[SearchCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[SelectCase]]></AName>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on 181300564/2021 link was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:17]]></Time>
<TimeTick>1618476197</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:43:11" eTime="15/04/2021 - 09:43:17" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="31" status="Passed" >
<Disp><![CDATA[SelectCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T25">
<AName><![CDATA[SelectRespondents]]></AName>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Next step's Visible Text contains Next step was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:20]]></Time>
<TimeTick>1618476200</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Select Respondent Details from Next step listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:22]]></Time>
<TimeTick>1618476202</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4: Click on Go button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:27]]></Time>
<TimeTick>1618476207</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:43:17" eTime="15/04/2021 - 09:43:27" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="34" status="Passed" >
<Disp><![CDATA[SelectRespondents Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[SelectAddNewRespondents]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Respondent Details's Visible Text contains Respondent Details was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:30]]></Time>
<TimeTick>1618476210</TimeTick>
<NodeArgs eType="General" icon="0" nRep="40" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.1: Click on Add new button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:33]]></Time>
<TimeTick>1618476213</TimeTick>
<NodeArgs eType="General" icon="0" nRep="41" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.2: Type Mr UI PerformanceTest in Name of respondent textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:40]]></Time>
<TimeTick>1618476220</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.3: Click on Yes  was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:43]]></Time>
<TimeTick>1618476223</TimeTick>
<NodeArgs eType="General" icon="0" nRep="43" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.4: Click on ACAS Certificate Number... textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:46]]></Time>
<TimeTick>1618476226</TimeTick>
<NodeArgs eType="General" icon="0" nRep="44" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.5: Type 001001001001 in ACAS Certificate Number... textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:52]]></Time>
<TimeTick>1618476232</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.6: Click on Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:54]]></Time>
<TimeTick>1618476234</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.7: Type SW1H 9HG in Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:43:59]]></Time>
<TimeTick>1618476239</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.8: Click on Find address button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:02]]></Time>
<TimeTick>1618476242</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[3.9: Select Flat 75, Vandon Court, 6...y France, London from Select an address listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:04]]></Time>
<TimeTick>1618476244</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.10: Click on Contact preference (Optio... label was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:07]]></Time>
<TimeTick>1618476247</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[3.11: Select Post from Contact preference (Optio... listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:10]]></Time>
<TimeTick>1618476250</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.12: Click on Yes  was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:12]]></Time>
<TimeTick>1618476252</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.13: Click on Yes  was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:15]]></Time>
<TimeTick>1618476255</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.14: Click on Day textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:18]]></Time>
<TimeTick>1618476258</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.15: Type 14 in Day textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:20]]></Time>
<TimeTick>1618476260</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.16: Click on Month textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:23]]></Time>
<TimeTick>1618476263</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.17: Type 4 in Month textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:24]]></Time>
<TimeTick>1618476264</TimeTick>
<NodeArgs eType="General" icon="0" nRep="57" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.18: Click on Year textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:27]]></Time>
<TimeTick>1618476267</TimeTick>
<NodeArgs eType="General" icon="0" nRep="58" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.19: Type 2021 in Year textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:29]]></Time>
<TimeTick>1618476269</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.20: Click on No  was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:32]]></Time>
<TimeTick>1618476272</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[3.21: Select Accepted from Response (Optional) listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:34]]></Time>
<TimeTick>1618476274</TimeTick>
<NodeArgs eType="General" icon="0" nRep="61" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.22: Click on No  was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:37]]></Time>
<TimeTick>1618476277</TimeTick>
<NodeArgs eType="General" icon="0" nRep="62" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.23: Click on Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:40]]></Time>
<TimeTick>1618476280</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[3.24: Type SW1H 9HG in Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:43]]></Time>
<TimeTick>1618476283</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.25: Click on Find address button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:46]]></Time>
<TimeTick>1618476286</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.26: Click on Find address button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:48]]></Time>
<TimeTick>1618476288</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Mouse Up]]></Obj>
<Details plainTxt="False" ><![CDATA[3.27: Mouse up on Town or City (Optional) label was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:51]]></Time>
<TimeTick>1618476291</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Mouse Up]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[3.28: Select Flat 75, Vandon Court, 6...y France, London from Select an address listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:44:54]]></Time>
<TimeTick>1618476294</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3.32: Click on Continue button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:01]]></Time>
<TimeTick>1618476301</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:43:27" eTime="15/04/2021 - 09:45:04" passed="30" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="39" status="Passed" >
<Disp><![CDATA[SelectAddNewRespondents Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T60">
<AName><![CDATA[SubmitNewRespondents]]></AName>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Click on Submit button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:09]]></Time>
<TimeTick>1618476309</TimeTick>
<NodeArgs eType="General" icon="0" nRep="72" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Verify has been updated with ev...spondent Details's Visible Text contains has been updated with ev...spondent Details was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:12]]></Time>
<TimeTick>1618476312</TimeTick>
<NodeArgs eType="General" icon="0" nRep="73" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="15/04/2021 - 09:45:04" eTime="15/04/2021 - 09:45:12" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="71" status="Passed" >
<Disp><![CDATA[SubmitNewRespondents Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T63">
<AName><![CDATA[CleanUp]]></AName>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Click on Case list link was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:15]]></Time>
<TimeTick>1618476315</TimeTick>
<NodeArgs eType="General" icon="0" nRep="76" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on 181300564/2021 link was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:21]]></Time>
<TimeTick>1618476321</TimeTick>
<NodeArgs eType="General" icon="0" nRep="77" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Select Respondent Details from Next step listbox was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:26]]></Time>
<TimeTick>1618476326</TimeTick>
<NodeArgs eType="General" icon="0" nRep="78" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[7: Click on Go button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:35]]></Time>
<TimeTick>1618476335</TimeTick>
<NodeArgs eType="General" icon="0" nRep="79" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[9: Click on Remove button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:41]]></Time>
<TimeTick>1618476341</TimeTick>
<NodeArgs eType="General" icon="0" nRep="80" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[10: Click on Remove button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:43]]></Time>
<TimeTick>1618476343</TimeTick>
<NodeArgs eType="General" icon="0" nRep="81" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[11: Click on Continue button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:47]]></Time>
<TimeTick>1618476347</TimeTick>
<NodeArgs eType="General" icon="0" nRep="82" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[12: Click on Submit button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:52]]></Time>
<TimeTick>1618476352</TimeTick>
<NodeArgs eType="General" icon="0" nRep="83" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[13: Click on Case list link was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:55]]></Time>
<TimeTick>1618476355</TimeTick>
<NodeArgs eType="General" icon="0" nRep="84" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[14: Click on Reset button was finished]]></Details>
<Time><![CDATA[15/04/2021 - 09:45:58]]></Time>
<TimeTick>1618476358</TimeTick>